[project]
name = "evan"
version = "2.0.0"
description = "Event assistant that helps you collect registration fees, manage attendees, and more."
authors = [
  {name = "Eneko Illarramendi", email = "eneko@illarra.com"}
]
license = {text = "MIT"}
requires-python = "~=3.14.0"
dependencies = [
  "commonmark",
  "django[bcrypt]>=6.0,<7.0",
  "django-allauth[socialaccount]",
  "django-compressor",
  "django-cors-headers",
  "django-countries",
  "django-ical",
  "django-libsass",
  "django-storages[s3]",
  "django-vite",
  "djangorestframework",
  "drf-extensions",
  "gunicorn",
  "huey",
  "inertia-django",
  "markdown",
  "mysqlclient",
  "nh3",
  "pillow",
  "polars",
  "pydantic",
  "pydantic-extra-types",
  "redis[hiredis]",
  "sentry-sdk[django]",
  "tld",
  "weasyprint",
  "whitenoise",
  "xlsxwriter",
  # this seems to be the latest valid version for UGent S3
  "boto3~=1.35.0",
  "botocore~=1.35.0",
  # only for badges
  "reportlab",
  "setuptools>=80.10.2",
  "svglib",
]

[dependency-groups]
dev = [
  "arrow",
  "django-debug-toolbar",
  "factory-boy",
  "fastexcel",
  "memray",
  "pytest",
  "pytest-cov",
  "pytest-django",
  "ruff",
]

[tool.coverage.run]
data_file = ".coverage_py/data"
omit = [
  "*/migrations/**",
  "*/settings/**",
  "*/tests/**",
  "*apps.py",
  "*urls.py",
  "*wsgi.py",
  "manage.py",
]

[tool.coverage.html]
directory = ".coverage_py"

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "def __repr__", "def __str__", "if TYPE_CHECKING:"]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov=evan"
markers = [
  "api: mark a test as an `api` test",
  "site: mark a test as an `site` test",
]
DJANGO_SETTINGS_MODULE = "evan.settings.test"

[tool.ruff]
target-version = "py314"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I", "DJ"]
ignore = ["SIM105"]

[tool.ruff.lint.isort]
lines-after-imports = 2
