# Generated by Django 5.1.5 on 2025-01-31 12:31

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models

import evan.models.rel.files
import evan.models.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliationDomain",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fld", models.CharField(max_length=190, unique=True)),
                ("affiliation", models.CharField(max_length=190)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                "db_table": "evan_log_fld",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_email", models.CharField(max_length=255)),
                ("to", models.JSONField(default=list)),
                ("bcc", models.JSONField(default=list)),
                ("reply_to", models.JSONField(default=list)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "evan_log_email",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "from_email",
                    models.CharField(
                        help_text="It can be a `Full Name &lt;email@domain.com&gt;` string or just an email address.",
                        max_length=128,
                        verbose_name="from",
                    ),
                ),
                ("bcc_email", models.EmailField(blank=True, default="", max_length=254, verbose_name="bcc")),
                ("reply_to_email", models.EmailField(blank=True, default="", max_length=254, verbose_name="reply-to")),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "action_name",
                    models.CharField(help_text="This text is shown on the admin area dropdowns.", max_length=128),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "evan_email_template",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("visa_requested", models.BooleanField(default=False)),
                ("visa_sent", models.BooleanField(default=False)),
                ("fee_type", models.CharField(max_length=16)),
                ("base_fee", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("extra_fees", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("manual_extra_fees", models.PositiveSmallIntegerField(default=0)),
                ("invoice_requested", models.BooleanField(default=False)),
                ("invoice_sent", models.BooleanField(default=False)),
                ("paid", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("paid_via_invoice", models.PositiveSmallIntegerField(default=0)),
                ("saldo", models.IntegerField(default=0, editable=False)),
                ("is_accepted", models.BooleanField(default=True, null=True)),
                ("extra_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=190)),
                ("max_capacity", models.PositiveSmallIntegerField(default=0)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "evan_venue_room",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead "
                        "of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("affiliation", models.CharField(blank=True, default="", max_length=190)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("extra_data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each "
                        "of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_virtual", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=32)),
                ("full_name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=160)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("presentation", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="")),
                ("hashtag", models.CharField(blank=True, default="", max_length=32)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_start_date", models.DateField()),
                ("registration_early_deadline", models.DateTimeField(blank=True, null=True)),
                ("registration_deadline", models.DateTimeField()),
                ("social_event_bundle_fee", models.PositiveSmallIntegerField(default=0)),
                ("signature", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("config", models.JSONField(default=dict)),
                ("extra_data", models.JSONField(default=dict)),
                ("custom_fields", models.JSONField(default=dict)),
                ("registrations_count", models.PositiveIntegerField(default=0)),
                ("accept_by_default", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["code"], name="evan_event_code_de03e5_idx"),
                    models.Index(fields=["start_date", "end_date"], name="evan_event_start_d_907dae_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "value",
                    models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=190)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="coupons", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["event", "id"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=32)),
                ("value", models.TextField(blank=True, default="")),
                ("config", models.JSONField(default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["event", "key"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=190)),
                ("affiliation", models.CharField(blank=True, default="", max_length=190)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("custom_color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="extra_badges", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["event", "name"],
            },
        ),
        migrations.CreateModel(
            name="Abstract",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=512)),
                ("authors", models.CharField(max_length=512)),
                ("abstract", models.TextField()),
                ("extra_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abstracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="abstracts", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=16)),
                ("value", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, default="", max_length=190)),
                ("is_early", models.BooleanField(default=False)),
                ("social_events_included", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fees", to="evan.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("type", models.CharField(choices=[("public", "Public"), ("private", "Private")], max_length=8)),
                ("file", models.FileField(upload_to=evan.models.rel.files.get_upload_path)),
                ("tags", models.JSONField(default=list, validators=[evan.models.validators.validate_list_of_strings])),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "db_table": "evan_rel_file",
                "ordering": ["content_type", "object_id"],
            },
        ),
        migrations.CreateModel(
            name="InvitationLetter",
            fields=[
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="letter",
                        serialize=False,
                        to="evan.registration",
                    ),
                ),
                ("name", models.CharField(max_length=190)),
                ("passport_number", models.CharField(max_length=60)),
                ("nationality", models.CharField(max_length=190)),
                ("address", models.TextField()),
                (
                    "submitted",
                    models.CharField(
                        blank=True, choices=[("paper", "Paper"), ("poster", "Poster")], default="", max_length=16
                    ),
                ),
                ("submitted_title", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddField(
            model_name="registration",
            name="coupon",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="evan.coupon"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="registrations", to="evan.event"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="registrations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("website", "Website"), ("linkedin", "LinkedIn"), ("other", "Other")],
                        default="website",
                        max_length=16,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "db_table": "evan_rel_link",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("stripe_charge", "Stripe charge"), ("stripe_refund", "Stripe refund")],
                        default="stripe_charge",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("pending", "Pending"), ("failed", "Failed")],
                        default="failed",
                        max_length=16,
                    ),
                ),
                ("outcome", models.TextField(blank=True, default="")),
                ("stripe_id", models.CharField(blank=True, default="", max_length=64)),
                ("stripe_response", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="evan.registration"
                    ),
                ),
            ],
            options={
                "db_table": "evan_log_payment",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.IntegerField()),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(9, "Owner"), (5, "Administrator"), (1, "Guest")], db_index=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="perms", to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evan_rel_permission",
                "ordering": ["content_type", "object_id", "-level"],
            },
        ),
        migrations.CreateModel(
            name="Remark",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "evan_rel_remark",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=32, null=True)),
                ("title", models.CharField(max_length=190)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "max_attendees",
                    models.PositiveSmallIntegerField(default=0, help_text="Leave on `0` for non limiting."),
                ),
                ("extra_attendees_fee", models.PositiveSmallIntegerField(default=0)),
                ("is_private", models.BooleanField(default=False)),
                ("is_social_event", models.BooleanField(default=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("extra_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="evan.event"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="evan.room",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at", "end_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="evan.registration"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="evan.session"
                    ),
                ),
            ],
            options={
                "db_table": "evan_log_registration",
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="sessions",
            field=models.ManyToManyField(blank=True, related_name="registrations", to="evan.session"),
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("website", models.URLField()),
                ("level", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sponsors", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["event", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="topics",
            field=models.ManyToManyField(blank=True, related_name="sessions", to="evan.topic"),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tracks", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="evan.track",
            ),
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_main", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(blank=True, default="", max_length=160)),
                ("presentation", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="venues", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ["event", "-is_main", "name"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="venue",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rooms", to="evan.venue"),
        ),
        migrations.CreateModel(
            name="AbstractReview",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("reviewed", "Reviewed"), ("finalized", "Finalized")],
                        default="assigned",
                        max_length=16,
                    ),
                ),
                ("evaluation", models.TextField(blank=True, default="")),
                (
                    "comments",
                    models.TextField(blank=True, default="", help_text="These can be shared with the applicant."),
                ),
                ("extra_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abstract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="evan.abstract"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abstract_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evan_abstract_review",
                "unique_together": {("abstract", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="evan_coupon_code_196326_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["event", "key"], name="evan_conten_event_i_935c38_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="content",
            unique_together={("event", "key")},
        ),
        migrations.AddIndex(
            model_name="fee",
            index=models.Index(fields=["type", "is_early"], name="evan_fee_type_f6ca07_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["file"], name="evan_rel_fi_file_9bccbe_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("content_type", "object_id", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="registrationlog",
            unique_together={("registration", "session")},
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(fields=["uuid"], name="evan_regist_uuid_df76cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("event", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("event", "code")},
        ),
    ]
