# Generated by Django 5.1.6 on 2025-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_config",
            field=models.JSONField(default=dict),
        ),
    ]
