# Generated by Django 5.1.6 on 2025-02-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0002_event_registration_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="registration",
            name="fee_type",
            field=models.CharField(max_length=64),
        ),
    ]
