# Generated by Django 5.1.7 on 2025-03-17 08:34

import django.db.models.deletion
from django.db import migrations, models

import evan.models.rel.validators


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0003_alter_fee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_templates",
                to="evan.event",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="tags",
            field=models.JSONField(default=list, validators=[evan.models.rel.validators.validate_list_of_strings]),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_logs",
                to="evan.event",
            ),
        ),
    ]
