# Generated by Django 2.1.7 on 2019-03-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0003_auto_20190321_1508"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("name", models.CharField(max_length=190)),
                (
                    "dietary",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "meal_preference"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_meal_preference",
                        to="evan.Metadata",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accompanying_persons",
                        to="evan.Registration",
                    ),
                ),
            ],
        ),
    ]
