# Generated by Django 5.1.7 on 2025-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0004_email_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
