# Generated by Django 5.1.7 on 2025-03-24 13:02

from django.db import migrations, models


def update_early_fees(apps, schema_editor) -> None:
    """For each non-early fee, check if an early variant exists, and update new fields."""

    Fee = apps.get_model("evan", "Fee")
    Session = apps.get_model("evan", "Session")

    for fee in Fee.objects.filter(is_early=True, event_id=24):
        fee.early_value = fee.value
        fee.is_early = False
        fee.save()

    for fee in Fee.objects.filter(is_early=False):
        early_fee = Fee.objects.filter(event=fee.event, type=fee.type, is_early=True).first()
        updated = False

        if fee.social_events_included:
            session_ids = Session.objects.filter(event=fee.event, is_social_event=True).values_list("id", flat=True)
            fee.config = {"included_social_events": list(session_ids)}
            updated = True

        if early_fee:
            fee.early_value = early_fee.value
            updated = True

        if updated:
            fee.save()

    for fee in Fee.objects.filter(is_early=True):
        fee.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0005_alter_session_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="early_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fee",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveIndex(
            model_name="fee",
            name="evan_fee_type_f6ca07_idx",
        ),
        # -----
        migrations.RunPython(update_early_fees),
        # -----
        migrations.RemoveField(
            model_name="fee",
            name="is_early",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="social_events_included",
        ),
        migrations.AddIndex(
            model_name="fee",
            index=models.Index(fields=["type"], name="evan_fee_type_91b486_idx"),
        ),
    ]
