# Generated by Django 5.1.7 on 2025-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0006_refactor_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="code",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("event", "code")},
        ),
    ]
