# Generated by Django 5.2 on 2025-05-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0007_alter_emailtemplate_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
