# Generated by Django 5.2 on 2025-05-08 14:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0008_file_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=190)),
                ("abstract", models.TextField(blank=True, default="")),
                ("doi", models.CharField(blank=True, default="", max_length=190)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="papers", to="evan.event"
                    ),
                ),
                ("topics", models.ManyToManyField(blank=True, related_name="papers", to="evan.topic")),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="papers",
                        to="evan.track",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "title")},
            },
        ),
    ]
