# Generated by Django 5.2 on 2025-05-13 13:59

import uuid

from django.db import migrations, models


def generate_unique_hashes(apps, schema_editor):
    Registration = apps.get_model("evan", "Registration")

    for registration in Registration.objects.all():
        registration.unique_hash = uuid.uuid4().hex[:8]
        registration.save()


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0009_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="unique_hash",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        # -----
        migrations.RunPython(generate_unique_hashes),
        # -----
    ]
