# Generated by Django 2.2 on 2019-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0010_invitationletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
