# Generated by Django 5.2.1 on 2025-06-03 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import evan.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0010_registration_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="tags",
            field=models.JSONField(default=list, validators=[evan.models.validators.validate_list_of_strings]),
        ),
        migrations.AddField(
            model_name="remark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="remark",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remarks_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
