# Generated by Django 2.2 on 2019-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0011_event_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="registrations_count", field=models.PositiveIntegerField(default=0),
        ),
    ]
