# Generated by Django 5.2.3 on 2025-06-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0011_remark_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="coverage",
            field=models.CharField(
                choices=[("base_fee", "Base fee"), ("all_fees", "All fees")],
                default="base_fee",
                help_text="What fees are covered by this coupon.",
                max_length=8,
            ),
        ),
    ]
