# Generated by Django 5.2.3 on 2025-06-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0012_coupon_coverage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="track",
        ),
        migrations.AddField(
            model_name="paper",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="papers",
                to="evan.session",
            ),
        ),
    ]
