# Generated by Django 5.2.3 on 2025-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0013_paper_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="program",
            field=models.TextField(blank=True, default=""),
        ),
    ]
