# Generated by Django 5.2.3 on 2025-06-16 12:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0014_session_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subsession",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=190, blank=True, default="")),
                ("program", models.TextField(blank=True, default="")),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=1, help_text="Order within the session")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subsessions", to="evan.session"
                    ),
                ),
            ],
            options={
                "ordering": ["session", "order", "start_at"],
                "unique_together": {("session", "order")},
            },
        ),
        migrations.AddField(
            model_name="paper",
            name="subsession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="papers",
                to="evan.subsession",
            ),
        ),
    ]
