# Generated by Django 5.2.3 on 2025-06-18 16:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0015_subsessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsession",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Keynote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Unique identifier (e.g., K1, KEYNOTE-AI)", max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("speaker", models.CharField(help_text="Speaker name", max_length=200)),
                ("bio", models.TextField(blank=True, default="", help_text="Speaker biography")),
                ("abstract", models.TextField(blank=True, default="", help_text="Keynote abstract or description")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="keynotes", to="evan.event"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keynotes",
                        to="evan.session",
                    ),
                ),
                (
                    "subsession",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keynotes",
                        to="evan.subsession",
                    ),
                ),
                ("topics", models.ManyToManyField(blank=True, related_name="keynotes", to="evan.topic")),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("event", "code")},
            },
        ),
    ]
