# Generated by Django 5.2.3 on 2025-06-24 09:21

from django.db import migrations, models


def migrate_venue_links_to_website(apps, schema_editor):
    """Migrate venue website links from the Link model to the new website field."""
    Venue = apps.get_model("evan", "Venue")
    Link = apps.get_model("evan", "Link")

    for venue in Venue.objects.all():
        website_links = Link.objects.filter(content_type__model="venue", object_id=venue.id, type="website")

        if website_links.exists():
            first_link = website_links.first()
            venue.website = first_link.url
            venue.save(update_fields=["website"])
            website_links.delete()


def reverse_migrate_venue_links(apps, schema_editor):
    """Reverse migration: move website field data back to Link model."""
    Venue = apps.get_model("evan", "Venue")
    Link = apps.get_model("evan", "Link")
    ContentType = apps.get_model("contenttypes", "ContentType")

    venue_content_type = ContentType.objects.get_for_model(Venue)

    for venue in Venue.objects.filter(website__isnull=False, website__gt=""):
        Link.objects.create(content_type=venue_content_type, object_id=venue.id, type="website", url=venue.website)
        venue.website = None
        venue.save(update_fields=["website"])


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0016_keynotes"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="website",
            field=models.URLField(blank=True, help_text="Website URL for the venue", verbose_name="Website"),
        ),
        migrations.AddField(
            model_name="venue",
            name="google_place_id",
            field=models.CharField(
                blank=True, help_text="Google Place ID for this venue", max_length=255, verbose_name="Google Place ID"
            ),
        ),
        # -----
        migrations.RunPython(
            migrate_venue_links_to_website,
            reverse_migrate_venue_links,
        ),
        # -----
    ]
