# Generated by Django 2.2.4 on 2019-08-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0016_auto_20190823_1036"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="content", unique_together={("event", "key")},),
    ]
