# Generated by Django 5.2.5 on 2025-08-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0017_venue_website_and_google_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="no_show",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="venue",
            name="google_place_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Places API place ID for enhanced location features",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
