# Generated by Django 3.0.8 on 2020-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0017_auto_20190823_1041"),
    ]

    operations = [
        migrations.AddField(model_name="event", name="custom_fields", field=models.TextField(default="{}"),),
        migrations.AddField(model_name="registration", name="custom_data", field=models.TextField(default="{}"),),
        migrations.AlterField(
            model_name="registration",
            name="days",
            field=models.ManyToManyField(blank=True, related_name="registrations", to="evan.Day"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="sessions",
            field=models.ManyToManyField(blank=True, related_name="registrations", to="evan.Session"),
        ),
    ]
