# Generated by Django 3.0.8 on 2020-07-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0019_profile_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="affiliation", field=models.CharField(blank=True, max_length=190, null=True),
        ),
    ]
