# Generated by Django 6.0.4 on 2026-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0020_add_onsite_fee_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="payid",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
