# Generated by Django 3.1.1 on 2020-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0020_auto_20200716_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allows_invoices',
            field=models.BooleanField(default=True),
        ),
    ]
