# Generated by Django 3.1.1 on 2020-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0021_event_allows_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='badge',
        ),
        migrations.AddField(
            model_name='event',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='registration',
            name='custom_data',
            field=models.JSONField(default=dict),
        ),
    ]
