# Generated by Django 6.0.4 on 2026-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0021_add_registration_payid"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="online_only",
            field=models.BooleanField(default=False),
        ),
    ]
