# Generated by Django 3.1.1 on 2020-09-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0023_hash_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(name="registration", options={"ordering": ("-id",)}),
    ]
