# Generated by Django 6.0.6 on 2026-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0023_registrationpaymentattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationpaymentattempt",
            options={},
        ),
        migrations.RenameIndex(
            model_name="registrationpaymentattempt",
            new_name="evan_log_re_registr_851714_idx",
            old_name="evan_regist_registr_0c2aab_idx",
        ),
        migrations.AddField(
            model_name="registration",
            name="invoice_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="registrationpaymentattempt",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
