# Generated by Django 3.1.5 on 2021-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0024_auto_20200930_1234"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="extra_data",
            new_name="main_config",
        ),
        migrations.AlterField(
            model_name="image",
            name="object_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="permission",
            name="object_id",
            field=models.IntegerField(),
        ),
    ]
