# Generated by Django 6.1 on 2026-08-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0025_rename_ingenico_salt_to_salt"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=190)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("from_email", models.CharField(default="UGent <evan@ugent.be>", max_length=128)),
                ("bcc_email", models.EmailField(blank=True, default="", max_length=254)),
                ("reply_to_email", models.EmailField(blank=True, default="", max_length=254)),
                ("filters", models.JSONField(default=dict)),
                ("send_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="email_plans", to="evan.event"
                    ),
                ),
            ],
            options={
                "db_table": "evan_email_plan",
                "ordering": ["-send_at", "-id"],
            },
        ),
    ]
