# Generated by Django 3.1.5 on 2021-01-21 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0025_auto_20210120_1654"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Paper",
        ),
    ]
