# Generated by Django 3.1.5 on 2021-01-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0026_delete_paper"),
    ]

    operations = [
        migrations.RemoveField(model_name="session", name="image",),
    ]
