# Generated by Django 6.1.1 on 2026-09-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import evan.models.users


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0026_emailplan"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", evan.models.users.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="decline_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="listing_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="listing_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listing_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="listing_status",
            field=models.CharField(
                choices=[("pending_review", "Pending review"), ("listed", "Listed"), ("declined", "Declined")],
                default="pending_review",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_audience",
            field=models.CharField(
                choices=[("public", "Public"), ("ugent_only", "UGent only")], default="public", max_length=32
            ),
        ),
    ]
