# Generated by Django 3.1.5 on 2021-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0027_remove_session_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-start_date",)},
        ),
        migrations.AddField(
            model_name="content",
            name="marked",
            field=models.BooleanField(default=True),
        ),
    ]
