# Generated by Django 3.1.7 on 2021-03-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0028_auto_20210129_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="full_name",
            field=models.CharField(max_length=200),
        ),
    ]
