# Generated by Django 3.2.3 on 2021-06-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0029_auto_20210308_2150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importantdate",
            name="event",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="days",
        ),
        migrations.AddField(
            model_name="event",
            name="custom_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="event",
            name="main_config",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="Day",
        ),
        migrations.DeleteModel(
            name="ImportantDate",
        ),
    ]
