# Generated by Django 3.2.3 on 2021-06-21 14:20

from datetime import datetime

from django.db import migrations, models
from django.utils.timezone import make_aware


def update_dates(apps, schema_editor):
    Session = apps.get_model("evan", "Session")
    for s in Session.objects.all():
        start_at = datetime(s.date.year, s.date.month, s.date.day, s.start_at.hour, s.start_at.minute)
        end_at = datetime(s.date.year, s.date.month, s.date.day, s.end_at.hour, s.end_at.minute)
        s.start_at = make_aware(start_at)
        s.end_at = make_aware(end_at)
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0030_auto_20210617_1411"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ("start_at", "end_at")},
        ),
        migrations.RemoveIndex(
            model_name="session",
            name="evan_sessio_event_i_fa353e_idx",
        ),
        migrations.AlterField(
            model_name="session",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        # -----------
        migrations.RunPython(update_dates),
        # -----------
        migrations.RemoveField(
            model_name="session",
            name="date",
        ),
    ]
