# Generated by Django 3.2.4 on 2021-06-23 06:55

from django.db import migrations, models


def migrate_metadata(apps, schema_editor):
    Person = apps.get_model("evan", "Person")
    Profile = apps.get_model("evan", "Profile")

    metadata = {
        1: "female",
        2: "male",
        3: "non_binary",
        7: "none",
        8: "vegetarian",
        9: "vegan",
        10: "kosher",
        11: "muslim",
        12: "intolerant_gluten",
        13: "intolerant_lactose",
        14: "allergic_crustaceans",
        15: "allergic_peanuts",
    }

    for p in Person.objects.all():
        p.custom_data = {"dietary": metadata[p.dietary_id] if p.dietary_id else None}
        p.save()

    for p in Profile.objects.all():
        p.custom_data = {
            "gender": metadata[p.gender_id] if p.gender_id else None,
            "dietary": metadata[p.dietary_id] if p.dietary_id else None,
        }
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0031_auto_20210621_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="custom_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="custom_data",
            field=models.JSONField(default=dict),
        ),
        # -----------
        migrations.RunPython(migrate_metadata),
        # -----------
        migrations.RemoveField(
            model_name="person",
            name="dietary",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="dietary",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.DeleteModel(
            name="Metadata",
        ),
    ]
