# Generated by Django 3.2.4 on 2021-06-25 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import evan.models.files
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evan", "0032_auto_20210623_0855"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abstract",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=512)),
                ("authors", models.CharField(max_length=512)),
                ("abstract", models.TextField()),
                ("custom_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="abstracts", to="evan.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abstracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("public", "Public"), ("private", "Private")], max_length=8)),
                ("file", models.FileField(upload_to=evan.models.files.get_upload_path)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={"ordering": ["content_type", "object_id"],},
        ),
        migrations.DeleteModel(name="Image",),
        migrations.AddIndex(model_name="file", index=models.Index(fields=["file"], name="evan_file_file_ea5cff_idx"),),
    ]
