# Generated by Django 3.2.4 on 2021-06-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0033_auto_20210625_1049"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="main_config",
            new_name="config",
        ),
    ]
