# Generated by Django 3.2.4 on 2021-06-26 14:04

from django.db import migrations, models


def migrate_config(apps, schema_editor):
    Content = apps.get_model("evan", "Content")

    for c in Content.objects.all():
        c.config = {"marked": c.marked, "uploader": False}
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0034_rename_main_config_event_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="config",
            field=models.JSONField(default=dict),
        ),
        # -----------
        migrations.RunPython(migrate_config),
        # -----------
        migrations.RemoveField(
            model_name="content",
            name="marked",
        ),
        migrations.RemoveField(
            model_name="content",
            name="notes",
        ),
    ]
