# Generated by Django 3.2.4 on 2021-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0035_connect_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="payments_activation", field=models.DateTimeField(blank=True, null=True),
        ),
    ]
