# Generated by Django 3.2.5 on 2021-07-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0036_event_payments_activation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("website", models.URLField()),
                ("level", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sponsors", to="evan.event"
                    ),
                ),
            ],
            options={"ordering": ("event", "level", "name")},
        ),
    ]
