# Generated by Django 3.2.6 on 2021-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0037_sponsor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="address",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="lng",
        ),
        migrations.AddField(
            model_name="venue",
            name="gmaps",
            field=models.URLField(blank=True, null=True),
        ),
    ]
