# Generated by Django 3.2.6 on 2021-08-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0038_auto_20210825_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('event', '-is_main', 'name')},
        ),
    ]
