# Generated by Django 3.2.6 on 2021-09-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0039_alter_venue_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
