# Generated by Django 3.2.7 on 2021-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0040_delete_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
