# Generated by Django 3.2.7 on 2021-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0041_file_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstract",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
