# Generated by Django 3.2.7 on 2021-09-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evan", "0042_abstract_is_accepted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abstract",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ("content_type", "object_id")},
        ),
        migrations.CreateModel(
            name="AbstractReview",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("reviewed", "Reviewed"), ("finalized", "Finalized")],
                        default="assigned",
                        max_length=16,
                    ),
                ),
                ("custom_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abstract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="evan.abstract"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abstract_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evan_abstract_review",
                "unique_together": {("abstract", "user")},
            },
        ),
    ]
