# Generated by Django 4.0.3 on 2022-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0044_alter_abstract_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
