# Generated by Django 4.0.3 on 2022-03-21 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0045_event_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="abstract",
            unique_together=set(),
        ),
    ]
