# Generated by Django 4.0.3 on 2022-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0046_alter_abstract_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="hashtag",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="fee",
            name="value",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
