# Generated by Django 4.0.3 on 2022-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0047_alter_event_hashtag_alter_fee_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="type",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="registration",
            name="fee_type",
            field=models.CharField(max_length=8),
        ),
    ]
