# Generated by Django 4.0.3 on 2022-04-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evan", "0048_alter_fee_type_alter_registration_fee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="fee_type",
            field=models.CharField(max_length=16),
        ),
    ]
