# Generated by Django 4.1.2 on 2022-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0050_abstractreview_comments_abstractreview_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="accept_by_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="is_accepted",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
