# Generated by Django 4.1.3 on 2022-12-01 14:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("evan", "0051_event_accept_by_default_registration_is_accepted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=190, null=True)),
                ("affiliation", models.CharField(blank=True, max_length=190, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="badges", to="evan.event"
                    ),
                ),
            ],
            options={
                "ordering": ("event", "name"),
            },
        ),
    ]
