# Generated by Django 4.2.7 on 2024-01-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0052_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='custom_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_badges', to='evan.event'),
        ),
    ]
