# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=160)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=16, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start_date', models.DateField()),
                ('registration_early_deadline', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=190, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='toucon.Conference')),
            ],
            options={
                'ordering': ['conference', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=190)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='toucon.Conference')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(9, 'Owner'), (5, 'Administrator'), (1, 'Guest')], db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xpermissions', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], db_index=True, max_length=1, null=True)),
                ('affiliation', models.CharField(max_length=190)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fee', models.PositiveSmallIntegerField(default=0)),
                ('saldo', models.SmallIntegerField(default=0)),
                ('visa_requested', models.BooleanField()),
                ('visa_sent', models.BooleanField(default=False)),
                ('invoice_requested', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='toucon.Conference')),
                ('coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toucon.Coupon')),
                ('days', models.ManyToManyField(related_name='registrations', to='toucon.Day')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='toucon.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('max_capacity', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_at', models.TimeField(blank=True, null=True)),
                ('end_at', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=190)),
                ('summary', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='public/sympo/activity')),
                ('max_attendees', models.PositiveSmallIntegerField(default=0, help_text='Leave on `0` for non limiting.')),
                ('extra_attendees_fee', models.PositiveSmallIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='toucon.Conference')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organized_sessions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='toucon.Room')),
            ],
            options={
                'ordering': ['date', 'start_at', 'end_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='toucon.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='toucon.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=160, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=160, null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('website', models.URLField(blank=True, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='toucon.Conference')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='toucon.Topic'),
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='toucon.Track'),
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='toucon.Venue'),
        ),
        migrations.AddField(
            model_name='registrationlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='toucon.Session'),
        ),
        migrations.AddField(
            model_name='registration',
            name='sessions',
            field=models.ManyToManyField(related_name='registrations', to='toucon.Session'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='xpermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='toucon.Registration'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['code'], name='toucon_conf_code_44d653_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['start_date', 'end_date'], name='toucon_conf_start_d_2df419_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationlog',
            unique_together=set([('registration', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('conference', 'user')]),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['conference', 'date'], name='toucon_day_confere_35a867_idx'),
        ),
    ]
