# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toucon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary',
            field=models.CharField(blank=True, choices=[('none', 'No special requirements'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('kosher', 'Kosher'), ('muslim', 'Muslim'), ('int_gluten', 'Gluten intolerant'), ('int_lactose', 'Lactose intolerant'), ('al_peanuts', 'Allergic to crustaceans'), ('al_peanuts', 'Allergic to peanuts')], db_index=True, max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='toucon_coup_code_a8499c_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['code'], name='toucon_regi_code_056dea_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['conference', 'date'], name='toucon_sess_confere_b0d648_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['conference', 'track'], name='toucon_sess_confere_dc6197_idx'),
        ),
    ]
