# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toucon', '0002_auto_20171113_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='badge',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
