# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toucon', '0003_conference_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'USD')], default='EUR', max_length=3),
        ),
    ]
