name: django-probe

on:
  schedule:
    - cron: "5 2 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  submit:
    uses: tim-schilling/django-probe/.github/workflows/django-probe-submit-uv.yml@0.4.0
    with:
      path: "."
      environment: ""
      python-version: ""
    secrets:
      DJANGO_PROBE_TOKEN: ${{ secrets.DJANGO_PROBE_TOKEN }}
